[package]
name = "fetch-prices"
version = "0.1.0"
authors = ["Markus Reiter <me@reitermark.us>"]
edition = "2018"

[[bin]]
name = "fetch_prices"
path = "src/fetch_prices.rs"

[[bin]]
name = "forecast"
path = "src/forecast.rs"

[dependencies]
serde = "1.0"
serde_json = "1.0"
anyhow = "1.0"
