version: '3.1'

services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
    container_name: db
    ports:
      - 3306:3306
  adminer:
    image: adminer
    ports:
      - 8080:8080
